version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gebow-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gebow
      POSTGRES_PASSWORD: gebow
      POSTGRES_DB: gebow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
